antdolg1/jg_java_1_wednesday_september_2022

src/main/java/students/student_ilja_morozovs/lesson_2/homework/level_6/Task_23/AttentionPlease.java
src/main/java/students/student_ilja_morozovs/lesson_2/homework/level_6/Task_24/NoSleepNoFocus.java

Add level 6 programs

---

src/main/java/students/student_oskars_popens/lesson_2/homework/level_1/Task2.java

Fix variable naming

---

src/main/java/students/student_aleksandrs_mads/lesson_2/homework/level_2/Task_3/Book.java
src/main/java/students/student_aleksandrs_mads/lesson_2/homework/level_2/Task_4/Phone.java
src/main/java/students/student_aleksandrs_mads/lesson_2/homework/level_2/Task_5/BankAccount.java
src/main/java/students/student_aleksandrs_mads/lesson_2/homework/level_2/Task_6/LoginService.java
src/main/java/students/student_aleksandrs_mads/lesson_2/homework/level_2/Task_7/LoginService.java
src/main/java/students/student_aleksandrs_mads/lesson_2/homework/level_2/Task_8/Name.java

Add lesson2 level2 Task3,4,5,6,7,8

homework lesson2 level2

---

src/main/java/students/student_ilja_morozovs/lesson_1/homework/level_4/Task_10/Greeting.java
src/main/java/students/student_ilja_morozovs/lesson_1/homework/level_4/Task_11/Divide.java
src/main/java/students/student_ilja_morozovs/lesson_1/homework/level_4/Task_11/NumSum.java
src/main/java/students/student_ilja_morozovs/lesson_1/homework/level_4/Task_12/Increase.java

Add lesson_1 level_4 file tree

Please check

---

src/main/java/students/student_aleksandrs_mads/lesson_2/homework/level_3/Task_10/AreaOfACircle.java
src/main/java/students/student_aleksandrs_mads/lesson_2/homework/level_3/Task_11/Average.java
src/main/java/students/student_aleksandrs_mads/lesson_2/homework/level_3/Task_9/MultiplicationTable.java

add lesson 2 level 3 task 9.10.11

homework lesson2 level3

---

src/main/java/students/student_ilja_morozovs/lessons_3/homework/level_2/Task_7/LearningUsingString.java
src/main/java/students/student_ilja_morozovs/lessons_3/homework/level_2/Task_8/Concatination.java
src/main/java/students/student_ilja_morozovs/lessons_3/homework/level_2/Task_9/ReadName.java

Add programm with String

---

src/main/java/students/student_ilja_morozovs/lessons_3/homework/level_3/Task_11/Robot.java
src/main/java/students/student_ilja_morozovs/lessons_3/homework/level_3/Task_11/RobotDemo.java
src/main/java/students/student_ilja_morozovs/lessons_3/homework/level_3/Task_12/Robot.java
src/main/java/students/student_ilja_morozovs/lessons_3/homework/level_3/Task_12/RobotDemo.java
src/main/java/students/student_ilja_morozovs/lessons_3/homework/level_3/Task_13/Robot.java
src/main/java/students/student_ilja_morozovs/lessons_3/homework/level_3/Task_13/RobotDemo.java

Add programm with robots... they can speak

Lessons 3 level_3

---

src/main/java/students/student_aleksandrs_mads/Summa.java
src/main/java/students/student_aleksandrs_mads/lesson_2/homework/level_1/Task_1.java
src/main/java/students/student_aleksandrs_mads/lesson_2/homework/level_1/Task_2.java

homework lesson2 level1

---

src/main/java/students/student_ilja_morozovs/lesson_3/homework/level_7/Task_29/PhoneBook.java
src/main/java/students/student_ilja_morozovs/lesson_3/homework/level_7/Task_29/PhoneBookDemo.java
src/main/java/students/student_ilja_morozovs/lesson_3/homework/level_7/Task_29/Tree.java
src/main/java/students/student_ilja_morozovs/lesson_3/homework/level_7/Task_29/TreeDemo.java
src/main/java/students/student_ilja_morozovs/lesson_3/homework/level_7/Task_30/Circle.java
src/main/java/students/student_ilja_morozovs/lesson_3/homework/level_7/Task_30/CircleDemo.java
src/main/java/students/student_ilja_morozovs/lesson_3/homework/level_7/Task_31/Product.java
src/main/java/students/student_ilja_morozovs/lesson_3/homework/level_7/Task_31/ProductDemo.java
src/main/java/students/student_ilja_morozovs/lesson_3/homework/level_7/Task_32/BankAccount.java
src/main/java/students/student_ilja_morozovs/lesson_3/homework/level_7/Task_32/BankAccountDemo.java
src/main/java/students/student_ilja_morozovs/lesson_3/homework/level_7/Task_33/Computer.java
src/main/java/students/student_ilja_morozovs/lesson_3/homework/level_7/Task_33/ComputerDemo.java
src/main/java/students/student_ilja_morozovs/lesson_4/homework/level_7/Task_22/FizzBuzz.java
src/main/java/students/student_ilja_morozovs/lesson_4/homework/level_7/Task_22/FizzBuzzTest.java
src/main/java/students/student_ilja_morozovs/lesson_4/homework/level_7/Task_22/FizzMain.java

St ilja morozovs lesson3 level7

---

src/main/java/students/student_deniss_fiscevs/lesson01/HellowWorld.java
src/main/java/students/student_deniss_fiscevs/lesson01/Lesson01_HelloWorld.java
src/main/java/students/student_deniss_fiscevs/lesson01/Lesson01_math.java
src/main/java/students/student_deniss_fiscevs/lesson01/Lesson01_math2.java
src/main/java/students/student_deniss_fiscevs/lesson01/Math.java
src/main/java/students/student_deniss_fiscevs/lesson01/Math2.java

Add lesson 01

---

src/main/java/students/student_deniss_fiscevs/lesson02/level_1_intern/Task_1.java
src/main/java/students/student_deniss_fiscevs/lesson02/level_1_intern/Task_2.java
src/main/java/students/student_deniss_fiscevs/lesson02/level_2_intern/Task_3.java
src/main/java/students/student_deniss_fiscevs/lesson02/level_2_intern/Task_4.java
src/main/java/students/student_deniss_fiscevs/lesson02/level_2_intern/Task_5.java
src/main/java/students/student_deniss_fiscevs/lesson02/level_2_intern/Task_6.java
src/main/java/students/student_deniss_fiscevs/lesson02/level_2_intern/Task_7.java
src/main/java/students/student_deniss_fiscevs/lesson02/level_2_intern/Task_8.java
src/main/java/students/student_deniss_fiscevs/lesson02/level_3_junior/Task_10.java
src/main/java/students/student_deniss_fiscevs/lesson02/level_3_junior/Task_11.java
src/main/java/students/student_deniss_fiscevs/lesson02/level_3_junior/Task_9.java

Fixed lesson 02 (separated from lesson 03)

Add lesson 02

---

src/main/java/students/student_ilja_morozovs/lesson_4/homework/level_1/Task_1/Number.java
src/main/java/students/student_ilja_morozovs/lesson_4/homework/level_1/Task_2/Number.java
src/main/java/students/student_ilja_morozovs/lesson_4/homework/level_1/Task_3/DayOfTheWeek.java
src/main/java/students/student_ilja_morozovs/lesson_4/homework/level_1/Task_4/Number.java

st ilja morozovs lesson4 level1

---

src/main/java/students/student_ilja_morozovs/lesson_4/homework/level_3/Task_10/LargestNumber.java
src/main/java/students/student_ilja_morozovs/lesson_4/homework/level_3/Task_8/ThreeEqualNumber.java
src/main/java/students/student_ilja_morozovs/lesson_4/homework/level_3/Task_9/ThreeNumbers.java

st ilja morozovs lesson4 level3

---

src/main/java/students/student_ilja_morozovs/lesson_4/homework/level_4/Task_11/Calculator.java
src/main/java/students/student_ilja_morozovs/lesson_4/homework/level_4/Task_12/Calculator.java
src/main/java/students/student_ilja_morozovs/lesson_4/homework/level_4/Task_12/CalculatorTest.java
src/main/java/students/student_ilja_morozovs/lesson_4/homework/level_4/Task_13/Calculator.java
src/main/java/students/student_ilja_morozovs/lesson_4/homework/level_4/Task_13/CalculatorTest.java
src/main/java/students/student_ilja_morozovs/lesson_4/homework/level_4/Task_14/Calculator.java
src/main/java/students/student_ilja_morozovs/lesson_4/homework/level_4/Task_14/CalculatorTest.java
src/main/java/students/student_ilja_morozovs/lesson_4/homework/level_4/Task_15/Calculator.java
src/main/java/students/student_ilja_morozovs/lesson_4/homework/level_4/Task_15/CalculatorTest.java

st ilja morozovs lesson4 level4

---

src/main/java/students/student_ilja_morozovs/lesson_4/homework/level_6/Task_17/Stock.java
src/main/java/students/student_ilja_morozovs/lesson_4/homework/level_6/Task_17/StockMain.java
src/main/java/students/student_ilja_morozovs/lesson_4/homework/level_6/Task_17/StockTest.java

add stock price program
add to class Stock method updatePrice
add manual test for this method;

Lesson 4, level6,Task_17

---

src/main/java/students/student_ilja_morozovs/lesson_5/homework/level_1/Task_1/ArrayDefinition1.java
src/main/java/students/student_ilja_morozovs/lesson_5/homework/level_1/Task_2/ArrayDefinition2.java
src/main/java/students/student_ilja_morozovs/lesson_5/homework/level_1/Task_3/ArrayDefenition3.java
src/main/java/students/student_ilja_morozovs/lesson_5/homework/level_1/Task_4/ArrayDefinition4.java
src/main/java/students/student_ilja_morozovs/lesson_5/homework/level_1/Task_5/ArrayDefinition5.java
src/main/java/students/student_ilja_morozovs/lesson_5/homework/level_1/Task_6/ArrayDefinition.java
src/main/java/students/student_ilja_morozovs/lesson_5/homework/level_1/Task_7/ArrayLenght1.java
src/main/java/students/student_ilja_morozovs/lesson_5/homework/level_1/Task_8/ArrayLenght2.java
src/main/java/students/student_ilja_morozovs/lesson_5/homework/level_1/Task_9/ArrayLenght3.java

st ilja morozovs lesson5 level1

---

src/main/java/students/student_ilja_morozovs/lesson_4/homework/level_5/Task_16/LightColorDetector.java
src/main/java/students/student_ilja_morozovs/lesson_4/homework/level_5/Task_16/LightColorDetectorTest.java
src/main/java/students/student_ilja_morozovs/lesson_4/homework/level_5/Task_16/LightDetector.java

add light detector program
add new method detect to LightColorDetector
add test for method detect in LightColorDetectorTest

Lesson 4, level5,Task_16

---

src/main/java/students/student_ilja_morozovs/lesson_5/homework/level_2/Task_10/NumbersArray.java
src/main/java/students/student_ilja_morozovs/lesson_5/homework/level_2/Task_11/UserNumberArray.java
src/main/java/students/student_ilja_morozovs/lesson_5/homework/level_2/Task_12/RandomNumberArray.java
src/main/java/students/student_ilja_morozovs/lesson_5/homework/level_2/Task_13/RandomNumArraySum.java
src/main/java/students/student_ilja_morozovs/lesson_5/homework/level_2/Task_14/RandomArrayMidNum.java
src/main/java/students/student_ilja_morozovs/lesson_5/homework/level_2/Task_15/RandomArray.java

st ilja morozovs lesson5 level2

---

src/main/java/students/student_ilja_morozovs/lesson_5/homework/level_5/Task_31/ArrayUtil.java
src/main/java/students/student_ilja_morozovs/lesson_5/homework/level_5/Task_32/ArrayUtil.java
src/main/java/students/student_ilja_morozovs/lesson_5/homework/level_5/Task_32/ArrayUtilTest.java
src/main/java/students/student_ilja_morozovs/lesson_5/homework/level_5/Task_33/ArrayUtil.java
src/main/java/students/student_ilja_morozovs/lesson_5/homework/level_5/Task_33/ArrayUtilTest.java

add some method with array creation and fill with random number

st ilja morozovs lesson5 level5

---

src/main/java/students/student_ilja_morozovs/lesson_5/homework/level_6/Task_34/ArrayUtil.java
src/main/java/students/student_ilja_morozovs/lesson_5/homework/level_6/Task_34/ArrayUtilTest.java
src/main/java/students/student_ilja_morozovs/lesson_5/homework/level_6/Task_36/ArrayUtil.java
src/main/java/students/student_ilja_morozovs/lesson_5/homework/level_6/Task_36/ArrayUtilTest.java
src/main/java/students/student_ilja_morozovs/lesson_5/homework/level_6/Task_37/ArrayUtil.java
src/main/java/students/student_ilja_morozovs/lesson_5/homework/level_6/Task_37/ArrayUtilTest.java
src/main/java/students/student_ilja_morozovs/lesson_5/homework/level_6/Task_38/ArrayUtil.java
src/main/java/students/student_ilja_morozovs/lesson_5/homework/level_6/Task_38/ArrayUtilTest.java

add programs with test methods

st ilja morozovs lesson5 level6

---

src/main/java/students/student_deniss_fiscevs/lesson07/level_1_intern/Task_1/WordService.java
src/main/java/students/student_deniss_fiscevs/lesson07/level_1_intern/Task_1/WordServiceApp.java
src/main/java/students/student_deniss_fiscevs/lesson07/level_1_intern/Task_1/WordServiceTest.java

Add lesson 07

---

src/main/java/students/student_ilja_morozovs/lesson_6/homework/level_1/Task_1/WhileDefinition1.java
src/main/java/students/student_ilja_morozovs/lesson_6/homework/level_1/Task_2/WhileDefinition2.java
src/main/java/students/student_ilja_morozovs/lesson_6/homework/level_1/Task_3/WhileDefinition3.java
src/main/java/students/student_ilja_morozovs/lesson_6/homework/level_1/Task_4/WhileDefinition4.java
src/main/java/students/student_ilja_morozovs/lesson_6/homework/level_1/Task_5/WhileDefinition5.java
src/main/java/students/student_ilja_morozovs/lesson_6/homework/level_1/Task_6/NumberUtils.java
src/main/java/students/student_ilja_morozovs/lesson_6/homework/level_1/Task_6/NumberUtilsTest.java

fix bugs
add test for method isEven

add lesson 6 level1 program

---

src/main/java/students/student_deniss_fiscevs/lesson03/level_1_intern/Robot.java
src/main/java/students/student_deniss_fiscevs/lesson03/level_1_intern/RobotDemo.java
src/main/java/students/student_deniss_fiscevs/lesson03/level_2_intern/Deniss.java
src/main/java/students/student_deniss_fiscevs/lesson03/level_3_junior/Robot.java
src/main/java/students/student_deniss_fiscevs/lesson03/level_3_junior/RobotDemo.java
src/main/java/students/student_deniss_fiscevs/lesson03/level_4_junior/BankAccount.java
src/main/java/students/student_deniss_fiscevs/lesson03/level_4_junior/BankAccountDemo.java
src/main/java/students/student_deniss_fiscevs/lesson03/level_4_junior/Book.java
src/main/java/students/student_deniss_fiscevs/lesson03/level_4_junior/BookDemo.java
src/main/java/students/student_deniss_fiscevs/lesson03/level_4_junior/Car.java
src/main/java/students/student_deniss_fiscevs/lesson03/level_4_junior/CarDemo.java
src/main/java/students/student_deniss_fiscevs/lesson03/level_4_junior/Phone.java
src/main/java/students/student_deniss_fiscevs/lesson03/level_4_junior/PhoneDemo.java
src/main/java/students/student_deniss_fiscevs/lesson03/level_5_middle/task_18/Dog.java
src/main/java/students/student_deniss_fiscevs/lesson03/level_5_middle/task_18/DogDemo.java
src/main/java/students/student_deniss_fiscevs/lesson03/level_5_middle/task_19/Dog.java
src/main/java/students/student_deniss_fiscevs/lesson03/level_5_middle/task_19/DogDemo.java
src/main/java/students/student_deniss_fiscevs/lesson03/level_5_middle/task_20/Dog.java
src/main/java/students/student_deniss_fiscevs/lesson03/level_5_middle/task_20/DogDemo.java
src/main/java/students/student_deniss_fiscevs/lesson03/level_5_middle/task_21/Dog.java
src/main/java/students/student_deniss_fiscevs/lesson03/level_5_middle/task_21/DogDemo.java
src/main/java/students/student_deniss_fiscevs/lesson03/level_5_middle/task_22/Dog.java
src/main/java/students/student_deniss_fiscevs/lesson03/level_5_middle/task_22/DogDemo.java

Add lesson 03 (without IDEA conflict)

---

src/main/java/students/student_ilja_morozovs/lesson_6/homework/level_2/Task_7/DayOfTheWeekDetectorDemo.java
src/main/java/students/student_ilja_morozovs/lesson_6/homework/level_2/Task_7/DayOfTheWeekDetectorDemoTest.java

complete all level 2 tasks in Task_7

st ilja morozovs lesson6 level2

---

src/main/java/students/student_ilja_morozovs/lesson_7/homework/level_1/Task_1/WordServise.java
src/main/java/students/student_ilja_morozovs/lesson_7/homework/level_1/Task_2/WordService.java
src/main/java/students/student_ilja_morozovs/lesson_7/homework/level_1/Task_2/WordServiceTest.java
src/main/java/students/student_ilja_morozovs/lesson_7/homework/level_1/Task_3/WordService.java

st.ilja morozovs lesson7 level1

---

src/main/java/students/student_ilja_morozovs/lesson_6/homework/level_4/Task_18/ForInfiniteLoop.java
src/main/java/students/student_ilja_morozovs/lesson_6/homework/level_4/Task_18/WhileInfiniteLoop.java
src/main/java/students/student_ilja_morozovs/lesson_6/homework/level_4/Task_19/ForInfiniteLoopBreak.java
src/main/java/students/student_ilja_morozovs/lesson_6/homework/level_4/Task_19/WhileInfiniteLoopBreak.java
src/main/java/students/student_ilja_morozovs/lesson_6/homework/level_4/Task_20/ForLoopContinue.java
src/main/java/students/student_ilja_morozovs/lesson_6/homework/level_4/Task_20/WhileLoopContinue.java
src/main/java/students/student_ilja_morozovs/lesson_6/homework/level_4/Task_21/TwoDimensionArrayUtil.java
src/main/java/students/student_ilja_morozovs/lesson_6/homework/level_4/Task_21/TwoDimensionalArray.java

complete lesson 6 level 4 tasks

st ilja morozovs lesson6 level4

---

src/main/java/students/student_oskars_popens/lesson_6/level_1_intern/NumberUtils.java
src/main/java/students/student_oskars_popens/lesson_6/level_1_intern/NumberUtilsTest.java
src/main/java/students/student_oskars_popens/lesson_6/level_1_intern/WhileDefinition1.java
src/main/java/students/student_oskars_popens/lesson_6/level_1_intern/WhileDefinition2.java
src/main/java/students/student_oskars_popens/lesson_6/level_1_intern/WhileDefinition3.java
src/main/java/students/student_oskars_popens/lesson_6/level_1_intern/WhileDefinition4.java
src/main/java/students/student_oskars_popens/lesson_6/level_1_intern/WhileDefinition5.java
src/main/java/students/student_oskars_popens/lesson_6/level_2_intern/DayOfTheWeekDetector.java
src/main/java/students/student_oskars_popens/lesson_6/level_2_intern/DayOfTheWeekDetectorDemo.java
src/main/java/students/student_oskars_popens/lesson_6/level_2_intern/DayOfTheWeekDetectorTest.java
src/main/java/students/student_oskars_popens/lesson_6/level_3_junior/ArrayService.java
src/main/java/students/student_oskars_popens/lesson_6/level_3_junior/ArrayServiceTest.java
src/main/java/students/student_oskars_popens/lesson_6/level_4_junior/ArrayService.java
src/main/java/students/student_oskars_popens/lesson_6/level_4_junior/ForInfiniteLoop.java
src/main/java/students/student_oskars_popens/lesson_6/level_4_junior/ForInfiniteLoopBreak.java
src/main/java/students/student_oskars_popens/lesson_6/level_4_junior/ForLoopContinue.java
src/main/java/students/student_oskars_popens/lesson_6/level_4_junior/TwoDimensionalArray.java
src/main/java/students/student_oskars_popens/lesson_6/level_4_junior/WhileInfiniteLoop.java
src/main/java/students/student_oskars_popens/lesson_6/level_4_junior/WhileInfiniteLoopBreak.java
src/main/java/students/student_oskars_popens/lesson_6/level_4_junior/WhileLoopContinue.java
src/main/java/students/student_oskars_popens/lesson_6/level_5_level_6/Move.java
src/main/java/students/student_oskars_popens/lesson_6/level_5_level_6/TicTacToe.java
src/main/java/students/student_oskars_popens/lesson_6/level_5_level_6/TicTacToeTest.java

Added lesson 6 code

---

src/main/java/students/student_deniss_fiscevs/lesson06/level_1_intern/NumberUtils.java
src/main/java/students/student_deniss_fiscevs/lesson06/level_1_intern/NumberUtilsTest.java
src/main/java/students/student_deniss_fiscevs/lesson06/level_1_intern/WhileDefinition1.java
src/main/java/students/student_deniss_fiscevs/lesson06/level_1_intern/WhileDefinition2.java
src/main/java/students/student_deniss_fiscevs/lesson06/level_1_intern/WhileDefinition3.java
src/main/java/students/student_deniss_fiscevs/lesson06/level_1_intern/WhileDefinition4.java
src/main/java/students/student_deniss_fiscevs/lesson06/level_1_intern/WhileDefinition5.java
src/main/java/students/student_deniss_fiscevs/lesson06/level_2_intern/DayOfTheWeekDetector.java
src/main/java/students/student_deniss_fiscevs/lesson06/level_2_intern/DayOfTheWeekDetectorDemo.java
src/main/java/students/student_deniss_fiscevs/lesson06/level_2_intern/DayOfTheWeekDetectorTest.java
src/main/java/students/student_deniss_fiscevs/lesson06/level_3_junior/Task_12/ArrayService.java
src/main/java/students/student_deniss_fiscevs/lesson06/level_3_junior/Task_12/ArrayServiceTest.java
src/main/java/students/student_deniss_fiscevs/lesson06/level_3_junior/Task_13/ArrayService.java
src/main/java/students/student_deniss_fiscevs/lesson06/level_3_junior/Task_13/ArrayServiceTest.java
src/main/java/students/student_deniss_fiscevs/lesson06/level_3_junior/Task_14/ArrayService.java
src/main/java/students/student_deniss_fiscevs/lesson06/level_3_junior/Task_14/ArrayServiceTest.java
src/main/java/students/student_deniss_fiscevs/lesson06/level_3_junior/Task_15/ArrayService.java
src/main/java/students/student_deniss_fiscevs/lesson06/level_3_junior/Task_15/ArrayServiceTest.java
src/main/java/students/student_deniss_fiscevs/lesson06/level_3_junior/Task_16/ArrayService.java
src/main/java/students/student_deniss_fiscevs/lesson06/level_3_junior/Task_16/ArrayServiceTest.java
src/main/java/students/student_deniss_fiscevs/lesson06/level_3_junior/Task_17/ArrayService.java
src/main/java/students/student_deniss_fiscevs/lesson06/level_3_junior/Task_17/ArrayServiceTest.java
src/main/java/students/student_deniss_fiscevs/lesson06/level_4_junior/Task_18/ForInfiniteLoop.java
src/main/java/students/student_deniss_fiscevs/lesson06/level_4_junior/Task_18/WhileInfiniteLoop.java
src/main/java/students/student_deniss_fiscevs/lesson06/level_4_junior/Task_19/ForInfiniteLoopBreak.java
src/main/java/students/student_deniss_fiscevs/lesson06/level_4_junior/Task_19/WhileInfiniteLoopBreak.java
src/main/java/students/student_deniss_fiscevs/lesson06/level_4_junior/Task_20/ForLoopContinue.java
src/main/java/students/student_deniss_fiscevs/lesson06/level_4_junior/Task_20/WhileLoopContinue.java
src/main/java/students/student_deniss_fiscevs/lesson06/level_4_junior/Task_21/TwoDimensionalArray.java

Add lesson 06

---

src/main/java/students/student_ilja_morozovs/lesson_7/level_5/Task_9/PowerCalculator.java
src/main/java/students/student_ilja_morozovs/lesson_7/level_5/Task_9/PowerCalculatorTest.java

st ilja morozovs lesson7 level5

---

src/main/java/students/student_oskars_popens/lesson_7/level_1_intern/WordService.java
src/main/java/students/student_oskars_popens/lesson_7/level_1_intern/WordServiceDemo.java
src/main/java/students/student_oskars_popens/lesson_7/level_1_intern/WordServiceTest.java
src/main/java/students/student_oskars_popens/lesson_7/level_5_middle/PowerCalculator.java
src/main/java/students/student_oskars_popens/lesson_7/level_5_middle/PowerCalculatorTest.java
src/main/java/students/student_oskars_popens/lesson_7/level_6_middle/ArrayCopy.java
src/main/java/students/student_oskars_popens/lesson_7/level_6_middle/ArrayCopyTest.java
src/main/java/students/student_oskars_popens/lesson_7/level_6_middle/CreditCard.java
src/main/java/students/student_oskars_popens/lesson_7/level_6_middle/CreditCardTest.java
src/main/java/students/student_oskars_popens/lesson_7/level_6_middle/Palindrome.java
src/main/java/students/student_oskars_popens/lesson_7/level_6_middle/PalindromeTest.java
src/main/java/students/student_oskars_popens/lesson_7/level_7_senior/WordService.java
src/main/java/students/student_oskars_popens/lesson_7/level_7_senior/WordServiceTest.java

Added lesson 7 homework

---

src/main/java/students/student_ilja_morozovs/lesson_8/homework/level_3/Task_10/FraudDetector.java
src/main/java/students/student_ilja_morozovs/lesson_8/homework/level_3/Task_10/FraudDetectorTest.java
src/main/java/students/student_ilja_morozovs/lesson_8/homework/level_3/Task_10/Trader.java
src/main/java/students/student_ilja_morozovs/lesson_8/homework/level_3/Task_10/Transaction.java
src/main/java/students/student_ilja_morozovs/lesson_8/homework/level_3/Task_11/FraudDetector.java
src/main/java/students/student_ilja_morozovs/lesson_8/homework/level_3/Task_11/FraudDetectorTest.java
src/main/java/students/student_ilja_morozovs/lesson_8/homework/level_3/Task_11/Trader.java
src/main/java/students/student_ilja_morozovs/lesson_8/homework/level_3/Task_11/Transaction.java
src/main/java/students/student_ilja_morozovs/lesson_8/homework/level_3/Task_12/FraudDetector.java
src/main/java/students/student_ilja_morozovs/lesson_8/homework/level_3/Task_12/FraudDetectorTest.java
src/main/java/students/student_ilja_morozovs/lesson_8/homework/level_3/Task_12/Trader.java
src/main/java/students/student_ilja_morozovs/lesson_8/homework/level_3/Task_12/Transaction.java
src/main/java/students/student_ilja_morozovs/lesson_8/homework/level_3/Task_9/FraudDetector.java
src/main/java/students/student_ilja_morozovs/lesson_8/homework/level_3/Task_9/FraudDetectorTest.java
src/main/java/students/student_ilja_morozovs/lesson_8/homework/level_3/Task_9/Trader.java
src/main/java/students/student_ilja_morozovs/lesson_8/homework/level_3/Task_9/Transaction.java

st ilja morozovs lesson8 level3
